CREATE SEQUENCE IF NOT EXISTS student_sequence;
ALTER SEQUENCE student_sequence RESTART WITH 6;

CREATE TABLE IF NOT EXISTS student(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(180),
    age INT
);